In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [4]:
df=pd.read_csv(r"C:\Users\USER\Name detection\Names_dataset.csv")

In [5]:
df.head()

name gender
0   sriram      m
1  vignesh      m
2  boomika      f
3   divya       f
4     somu      m

In [6]:
df.size

250462

In [7]:
df.columns

Index(['name', 'gender'], dtype='object')

In [8]:
df.dtypes

name      object
gender    object
dtype: object

In [9]:
df.isnull().isnull().sum()

name      0
gender    0
dtype: int64

In [10]:
df[df.gender=="f"].size

151934

In [11]:
df[df.gender=="m"].size

98528

In [12]:
df_names=df

In [13]:
df_names.gender.replace({'f':0,'m':1},inplace=True)

In [14]:
df.head()

name  gender
0   sriram       1
1  vignesh       1
2  boomika       0
3   divya        0
4     somu       1

In [15]:
df_names.gender.unique()

array([1, 0], dtype=int64)

In [16]:
df_names['gender'].unique()

array([1, 0], dtype=int64)

In [17]:
df_names.dtypes

name      object
gender     int64
dtype: object

In [18]:
Xfeatures= df_names['name']

In [19]:
from re import X
cv=CountVectorizer()
X=cv.fit_transform(Xfeatures.values.astype('U'))

In [20]:
X

<125231x101781 sparse matrix of type '<class 'numpy.int64'>'
	with 141359 stored elements in Compressed Sparse Row format>

In [21]:
X.shape

(125231, 101781)

In [22]:
gender_vectorizer= open("gender_vectorizer.pkl","wb")
joblib.dump(cv,gender_vectorizer)

In [23]:
gender_vectorizer.close()

In [24]:
cv.get_feature_names_out()

array(['aaban', 'aabha', 'aabid', ..., 'सर', 'सलम', 'हन'], dtype=object)

In [25]:
y=df_names.gender

In [26]:
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2,random_state=42)

In [27]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

0.9913758684021401

In [28]:
print("Accuracy of Model-> {} %".format(clf.score(X_test, y_test)*100))

Accuracy of Model-> 71.05841018884497 %


In [29]:
print("Accuracy of Model-> {} %".format(clf.score(X_train, y_train)*100))

Accuracy of Model-> 99.13758684021401 %


In [30]:
sample_names=["sriram"]
vect=cv.transform(sample_names).toarray()
clf.predict(vect)

array([1], dtype=int64)

In [31]:
sample_names2=["pooja ramanan"]
vect=cv.transform(sample_names2).toarray()
clf.predict(vect)

array([0], dtype=int64)

In [32]:
sample_names3=['boomika','divya','vignesh','dharveh','siva']
vect=cv.transform(sample_names3).toarray()
clf.predict(vect)

array([0, 0, 1, 1, 1], dtype=int64)

In [33]:
def  gender_predictor(name):
  test_name=[name]
  vector= cv.transform(test_name).toarray()
  if clf.predict(vector)==0:
    return "Female"
  else:
     return "Male"


In [34]:
gender_predictor("pooja ramanan")

'Female'

In [35]:
for i in sample_names3:
  print(i,"->",gender_predictor(i))


boomika -> Female
divya -> Female
vignesh -> Male
dharveh -> Male
siva -> Male


In [36]:
def features(name):
  name=str(name)
  name=name.lower()
  return{
      'first-letter':name[0],
      'first2-letter':name[0:2],
      'first3-letter':name[0:3],
      'last-letter':name[-1],
      'last2-letter':name[-2:],
      'last3-letter':name[-3:],
  }


In [37]:
features = np.vectorize(features) # Assign the vectorized function to a new variable
features(['boomika','divya','vignesh','dharveh','siva']) # Call the vectorized function

array([{'first-letter': 'b', 'first2-letter': 'bo', 'first3-letter': 'boo', 'last-letter': 'a', 'last2-letter': 'ka', 'last3-letter': 'ika'},
       {'first-letter': 'd', 'first2-letter': 'di', 'first3-letter': 'div', 'last-letter': 'a', 'last2-letter': 'ya', 'last3-letter': 'vya'},
       {'first-letter': 'v', 'first2-letter': 'vi', 'first3-letter': 'vig', 'last-letter': 'h', 'last2-letter': 'sh', 'last3-letter': 'esh'},
       {'first-letter': 'd', 'first2-letter': 'dh', 'first3-letter': 'dha', 'last-letter': 'h', 'last2-letter': 'eh', 'last3-letter': 'veh'},
       {'first-letter': 's', 'first2-letter': 'si', 'first3-letter': 'siv', 'last-letter': 'a', 'last2-letter': 'va', 'last3-letter': 'iva'}],
      dtype=object)

In [38]:
df_X=features(df_names['name'])

In [39]:
df_y=features(df_names['gender'])

In [40]:
corpus=features(["veebula ramanan","somu"])
dv=DictVectorizer()
dv.fit(corpus)
transformed=dv.transform(corpus)

In [41]:
print(transformed)

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 6)	1.0
  (0, 8)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 7)	1.0
  (1, 9)	1.0
  (1, 11)	1.0


In [42]:
dv.get_feature_names_out()

array(['first-letter=s', 'first-letter=v', 'first2-letter=so',
       'first2-letter=ve', 'first3-letter=som', 'first3-letter=vee',
       'last-letter=n', 'last-letter=u', 'last2-letter=an',
       'last2-letter=mu', 'last3-letter=nan', 'last3-letter=omu'],
      dtype=object)

In [43]:
dfX_train,dfX_test,dfy_train,dfy_test=train_test_split(df_X,df_y,test_size=0.2,random_state=42)

In [44]:
dfX_train

array([{'first-letter': 't', 'first2-letter': 'te', 'first3-letter': 'tem', 'last-letter': 'a', 'last2-letter': 'ca', 'last3-letter': 'eca'},
       {'first-letter': 'm', 'first2-letter': 'ma', 'first3-letter': 'mar', 'last-letter': 'd', 'last2-letter': 'id', 'last3-letter': 'rid'},
       {'first-letter': 'a', 'first2-letter': 'av', 'first3-letter': 'ava', 'last-letter': 'e', 'last2-letter': 'se', 'last3-letter': 'ose'},
       ...,
       {'first-letter': 'n', 'first2-letter': 'ny', 'first3-letter': 'nya', 'last-letter': 'l', 'last2-letter': 'al', 'last3-letter': 'yal'},
       {'first-letter': 't', 'first2-letter': 'ti', 'first3-letter': 'tin', 'last-letter': 'a', 'last2-letter': 'ya', 'last3-letter': 'iya'},
       {'first-letter': 'a', 'first2-letter': 'ab', 'first3-letter': 'abb', 'last-letter': 'l', 'last2-letter': 'el', 'last3-letter': 'ael'}],
      dtype=object)

In [45]:
dv=DictVectorizer()
dv.fit_transform(dfX_train)

<100184x9284 sparse matrix of type '<class 'numpy.float64'>'
	with 601104 stored elements in Compressed Sparse Row format>

In [46]:
from sklearn.tree import DecisionTreeClassifier
dclf = DecisionTreeClassifier()
x_features = dv.transform(dfX_train)
dclf.fit(x_features, dfy_train)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [47]:
DecisionTreeClassifier()

DecisionTreeClassifier()

In [48]:
sample_name_eg=["somu"]
transform_dv=dv.transform(features(sample_name_eg)).toarray()
dclf.predict(transform_dv)

AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

In [49]:
decistion_tree = open("decisiontree.pkl","wb")

In [50]:
import pickle
decistion_tree_01 = open("name_detector_model.pkl","wb")
pickle.dump(dclf, decistion_tree_01)
decistion_tree_01.close()

In [52]:
naive_bayes =  open("naivebayes.pkl","wb")
joblib.dump(clf, naive_bayes)
naive_bayes.close()